In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel('crowd.xlsx')

In [3]:
data.head()

,Date,Time,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Special_Features,Region,Transportation_Type
0,2024-01-01,14:56:00,"Sanchi Stupa, Madhya Pradesh",825,Cloudy,Monday,Yes,Cultural Event,39,0,National Holiday,West,Walking
1,2024-01-02,00:48:00,"Qutub Minar, Delhi",8962,Cloudy,Tuesday,No,Regular Day,30,0,NaN,South,Private
2,2024-01-03,02:06:00,"Varanasi Ghats, Varanasi",10000,Clear,Wednesday,No,Regular Day,32,0,NaN,South,Public
3,2024-01-04,20:39:00,"Qutub Minar, Delhi",18632,Sunny,Thursday,No,Festival,24,0,NaN,West,Private
4,2024-01-05,05:38:00,"Red Fort, Delhi",5155,Rainy,Friday,No,Cultural Event,39,0,NaN,East,Walking

In [4]:
data.describe

<bound method NDFrame.describe of            Date      Time                         Place  \
0    2024-01-01  14:56:00  Sanchi Stupa, Madhya Pradesh
1    2024-01-02  00:48:00            Qutub Minar, Delhi
2    2024-01-03  02:06:00      Varanasi Ghats, Varanasi
3    2024-01-04  20:39:00            Qutub Minar, Delhi
4    2024-01-05  05:38:00               Red Fort, Delhi
..          ...       ...                           ...
725  2025-12-26  03:15:00            Qutub Minar, Delhi
726  2025-12-27  14:46:00               Taj Mahal, Agra
727  2025-12-28  02:55:00      Varanasi Ghats, Varanasi
728  2025-12-29  04:52:00  Sanchi Stupa, Madhya Pradesh
729  2025-12-30  10:26:00  Sanchi Stupa, Madhya Pradesh

     Crowd_Count (in Thousands) Weather Day_of_Week Holiday             Event  \
0                           825  Cloudy      Monday     Yes    Cultural Event
1                          8962  Cloudy     Tuesday      No       Regular Day
2                         10000   Clear   Wednesday      No       Regular Day
3                         18632   Sunny    Thursday      No          Festival
4                          5155   Rainy      Friday      No    Cultural Event
..                          ...     ...         ...     ...               ...
725                       10000   Clear      Friday      No       Regular Day
726                       34003   Clear    Saturday      No  National Holiday
727                       12730   Sunny      Sunday      No       Regular Day
728                       18950   Rainy      Monday      No          Festival
729                       15469  Cloudy     Tuesday      No  National Holiday

     Temperature (°C)  Week_of_Year  Special_Features   Region  \
0                  39             0  National Holiday     West
1                  30             0               NaN    South
2                  32             0               NaN    South
3                  24             0               NaN     West
4                  39             0               NaN     East
..                ...           ...               ...      ...
725                32            51               NaN    North
726                24            51               NaN    South
727                37            52               NaN    North
728                31            52               NaN  Central
729                38            52               NaN    North

    Transportation_Type
0               Walking
1               Private
2                Public
3               Private
4               Walking
..                  ...
725              Public
726              Public
727              Public
728             Private
729             Walking

[730 rows x 13 columns]>

In [5]:
data.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        730 non-null    object
 1   Time                        730 non-null    object
 2   Place                       730 non-null    object
 3   Crowd_Count (in Thousands)  730 non-null    int64
 4   Weather                     730 non-null    object
 5   Day_of_Week                 730 non-null    object
 6   Holiday                     730 non-null    object
 7   Event                       730 non-null    object
 8   Temperature (°C)            730 non-null    int64
 9   Week_of_Year                730 non-null    int64
 10  Special_Features            47 non-null     object
 11  Region                      730 non-null    object
 12  Transportation_Type         730 non-null    object
dtypes: int64(3), object(10)
memory usage: 74.3+ KB

In [6]:
data.drop(columns='Special_Features',inplace = True)

In [7]:
data.head()

,Date,Time,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type
0,2024-01-01,14:56:00,"Sanchi Stupa, Madhya Pradesh",825,Cloudy,Monday,Yes,Cultural Event,39,0,West,Walking
1,2024-01-02,00:48:00,"Qutub Minar, Delhi",8962,Cloudy,Tuesday,No,Regular Day,30,0,South,Private
2,2024-01-03,02:06:00,"Varanasi Ghats, Varanasi",10000,Clear,Wednesday,No,Regular Day,32,0,South,Public
3,2024-01-04,20:39:00,"Qutub Minar, Delhi",18632,Sunny,Thursday,No,Festival,24,0,West,Private
4,2024-01-05,05:38:00,"Red Fort, Delhi",5155,Rainy,Friday,No,Cultural Event,39,0,East,Walking

In [8]:
data['isWeekend'] = data['Day_of_Week'].isin(['Sunday', 'Saturday']).astype(int)

In [9]:
data.head(2)

,Date,Time,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type,isWeekend
0,2024-01-01,14:56:00,"Sanchi Stupa, Madhya Pradesh",825,Cloudy,Monday,Yes,Cultural Event,39,0,West,Walking,0
1,2024-01-02,00:48:00,"Qutub Minar, Delhi",8962,Cloudy,Tuesday,No,Regular Day,30,0,South,Private,0

In [10]:
data['State'] = data['Place'].str.split(',').str[1].str.strip()

In [11]:
data.head(2)

,Date,Time,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type,isWeekend,State
0,2024-01-01,14:56:00,"Sanchi Stupa, Madhya Pradesh",825,Cloudy,Monday,Yes,Cultural Event,39,0,West,Walking,0,Madhya Pradesh
1,2024-01-02,00:48:00,"Qutub Minar, Delhi",8962,Cloudy,Tuesday,No,Regular Day,30,0,South,Private,0,Delhi

In [12]:
# LinearRegressor
# LogisticRegressor
# DicisionTreeClassifire
# RandomForestClassifire
# XGBoost
# LightGBM

In [13]:
data['Place'] = data['Place'].str.split(',').str[0].str.strip()

In [14]:
data.head()

,Date,Time,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type,isWeekend,State
0,2024-01-01,14:56:00,Sanchi Stupa,825,Cloudy,Monday,Yes,Cultural Event,39,0,West,Walking,0,Madhya Pradesh
1,2024-01-02,00:48:00,Qutub Minar,8962,Cloudy,Tuesday,No,Regular Day,30,0,South,Private,0,Delhi
2,2024-01-03,02:06:00,Varanasi Ghats,10000,Clear,Wednesday,No,Regular Day,32,0,South,Public,0,Varanasi
3,2024-01-04,20:39:00,Qutub Minar,18632,Sunny,Thursday,No,Festival,24,0,West,Private,0,Delhi
4,2024-01-05,05:38:00,Red Fort,5155,Rainy,Friday,No,Cultural Event,39,0,East,Walking,0,Delhi

In [15]:
data['Date'] = pd.to_datetime(data['Date'])

In [16]:
data['Time']=pd.to_datetime(data['Time'],format='%H:%M:%S')

In [17]:
data['hour'] = data['Time'].dt.hour
data['month'] = data['Date'].dt.month
data['day'] = data['Date'].dt.day

In [18]:
data.head(2)

,Date,Time,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type,isWeekend,State,hour,month,day
0,2024-01-01,1900-01-01 14:56:00,Sanchi Stupa,825,Cloudy,Monday,Yes,Cultural Event,39,0,West,Walking,0,Madhya Pradesh,14,1,1
1,2024-01-02,1900-01-01 00:48:00,Qutub Minar,8962,Cloudy,Tuesday,No,Regular Day,30,0,South,Private,0,Delhi,0,1,2

In [19]:
data.drop(columns='Time',inplace = True, axis=1)

In [20]:
data.head()

,Date,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type,isWeekend,State,hour,month,day
0,2024-01-01,Sanchi Stupa,825,Cloudy,Monday,Yes,Cultural Event,39,0,West,Walking,0,Madhya Pradesh,14,1,1
1,2024-01-02,Qutub Minar,8962,Cloudy,Tuesday,No,Regular Day,30,0,South,Private,0,Delhi,0,1,2
2,2024-01-03,Varanasi Ghats,10000,Clear,Wednesday,No,Regular Day,32,0,South,Public,0,Varanasi,2,1,3
3,2024-01-04,Qutub Minar,18632,Sunny,Thursday,No,Festival,24,0,West,Private,0,Delhi,20,1,4
4,2024-01-05,Red Fort,5155,Rainy,Friday,No,Cultural Event,39,0,East,Walking,0,Delhi,5,1,5

In [21]:
data['Holiday'] = data['Holiday'].map({"Yes":1,"No":0})

In [22]:
data['Weather'].unique()

array(['Cloudy', 'Clear', 'Sunny', 'Rainy'], dtype=object)

In [23]:
new_data = data.drop(columns='Date',axis = 1)

In [24]:
new_data.head(2)

,Place,Crowd_Count (in Thousands),Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type,isWeekend,State,hour,month,day
0,Sanchi Stupa,825,Cloudy,Monday,1,Cultural Event,39,0,West,Walking,0,Madhya Pradesh,14,1,1
1,Qutub Minar,8962,Cloudy,Tuesday,0,Regular Day,30,0,South,Private,0,Delhi,0,1,2

In [25]:
all_categorical_columns = new_data.select_dtypes(include = ['object']).columns

In [26]:
all_categorical_columns

Index(['Place', 'Weather', 'Day_of_Week', 'Event', 'Region',
       'Transportation_Type', 'State'],
      dtype='object')

In [27]:
y=data['Crowd_Count (in Thousands)']
x= data.drop(columns = ['Crowd_Count (in Thousands)'])

In [28]:
y = y/(max(y))

In [29]:
y.head()

0    0.01650
1    0.17924
2    0.20000
3    0.37264
4    0.10310
Name: Crowd_Count (in Thousands), dtype: float64

In [30]:
# Column_Transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [31]:
preprocessor = ColumnTransformer(
    transformers= [('cat',OneHotEncoder(),all_categorical_columns)]
)

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
from sklearn.pipeline import Pipeline

In [34]:
model = Pipeline(
    steps =[
        ('preprocess',preprocessor),
        ('regressor',LinearRegression())
    ]
)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.29,random_state=42 )

In [37]:
model.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Place', 'Weather', 'Day_of_Week', 'Event', 'Region',
       'Transportation_Type', 'State'],
      dtype='object'))])),
                ('regressor', LinearRegression())])

In [38]:
y_pred = model.predict(x_test)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2:", r2)

MSE: 0.004811047134254515
R2: 0.9033044825040875

In [41]:
x_train.head()

,Date,Place,Weather,Day_of_Week,Holiday,Event,Temperature (°C),Week_of_Year,Region,Transportation_Type,isWeekend,State,hour,month,day
176,2024-06-25,Qutub Minar,Rainy,Tuesday,0,Cultural Event,30,25,West,Public,0,Delhi,22,6,25
381,2025-01-16,Taj Mahal,Cloudy,Thursday,0,National Holiday,38,2,Central,Public,0,Agra,18,1,16
332,2024-11-28,Qutub Minar,Sunny,Thursday,0,Festival,24,47,Central,Private,0,Delhi,23,11,28
532,2025-06-16,Mecca Masjid,Clear,Monday,0,National Holiday,35,24,North,Private,0,Hyderabad,12,6,16
558,2025-07-12,India Gate,Clear,Saturday,0,National Holiday,36,27,West,Private,1,Delhi,16,7,12

In [42]:
# Ridge and Lasso
from sklearn.linear_model import Ridge,Lasso

In [43]:
ridge_model = Ridge(1.0)
lasso_model = Lasso(0.1)

In [44]:
pipeline_1 = Pipeline(
    steps = [
        ('preprocess', preprocessor),
        ('model', ridge_model)])

In [45]:
pipeline_2 = Pipeline(
    steps = [
        ('preprocess', preprocessor),
        ('model', lasso_model)])

In [46]:
pipeline_1.fit(x_train,y_train)
pipeline_2.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Place', 'Weather', 'Day_of_Week', 'Event', 'Region',
       'Transportation_Type', 'State'],
      dtype='object'))])),
                ('model', Lasso(alpha=0.1))])

In [47]:
r_pred = pipeline_1.predict(x_test)
l_pred = pipeline_2.predict(x_test)

In [48]:
r = r2_score(y_test,r_pred)
l = r2_score(y_test,l_pred)

In [49]:
print(r,l)

0.9031760522247486 -0.003522322496389396

In [50]:
new_l = mean_squared_error(y_test,l_pred)

In [51]:
new_l

0.04992985526977273

In [52]:
# Decision Tree Classifier

In [53]:
from sklearn.tree import DecisionTreeRegressor

In [54]:
pipeline_3 = Pipeline(
    steps=[
        ('preprocess',preprocessor),
        ('model',DecisionTreeRegressor())
    ]
)

In [55]:
pipeline_3.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Place', 'Weather', 'Day_of_Week', 'Event', 'Region',
       'Transportation_Type', 'State'],
      dtype='object'))])),
                ('model', DecisionTreeRegressor())])

In [56]:
y_pred = pipeline_3.predict(x_test)

In [57]:
r2_score(y_test,y_pred)

0.8090593426408664

In [58]:
from sklearn.ensemble import RandomForestRegressor

In [59]:
pipeline_4 = Pipeline(
    steps = [
        ('preprocess',preprocessor),
        ('model',RandomForestRegressor())
    ]
)

In [60]:
pipeline_4.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Place', 'Weather', 'Day_of_Week', 'Event', 'Region',
       'Transportation_Type', 'State'],
      dtype='object'))])),
                ('model', RandomForestRegressor())])

In [61]:
y_pred = pipeline_4.predict(x_test)

In [62]:
r2_score(y_test,y_pred)

0.8955270232918161

In [63]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\chaud\appdata\local\programs\python\python313\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\chaud\appdata\local\programs\python\python313\lib\site-packages (from lightgbm) (2.2.2)
Requirement already satisfied: scipy in c:\users\chaud\appdata\local\programs\python\python313\lib\site-packages (from lightgbm) (1.15.1)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
from xgboost import XGBRegressor

In [65]:
pipeline_5 = Pipeline(
    steps=[
        ('preprocess',preprocessor),
        ('model',XGBRegressor())
    ])

In [66]:
pipeline_5.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Place', 'Weather', 'Day_of_Week', 'Event', 'Region',
       'Transportation_Type', 'State'],
      dtype='object'))])),
                ('model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stoppin...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [67]:
y_pred = pipeline_5.predict(x_test)

In [68]:
r2_score(y_test,y_pred)

0.8674913801050215

In [69]:
import lightgbm as lgb

In [70]:
pipeline_6 = Pipeline(
    steps=[
        ('preprocess',preprocessor),
        ('model',lgb.LGBMRegressor())
    ])

In [71]:
pipeline_6.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000134 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 518, number of used features: 37
[LightGBM] [Info] Start training from score 0.368183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Place', 'Weather', 'Day_of_Week', 'Event', 'Region',
       'Transportation_Type', 'State'],
      dtype='object'))])),
                ('model', LGBMRegressor())])

In [72]:
y_pred = pipeline_6.predict(x_test)

C:\Users\chaud\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [73]:
r2_score(y_test,y_pred)

0.8760255604384773

In [74]:
mean_squared_error(y_test,y_pred)

0.006168299085823555

In [75]:
y_train_pred= pipeline_6.predict(x_train)

C:\Users\chaud\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [76]:
r2_score(y_train,y_train_pred)

0.9470947920757886

In [77]:
y_train_pred_linear = model.predict(x_train)

In [78]:
r2_score(y_train,y_train_pred_linear)

0.9200899277893797

In [79]:
import pickle

In [81]:
with open("crowd_model.pkl", "wb") as f:
    pickle.dump(pipeline_6, f)